-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg6H8yDwjTJDqdoUCd
oACLPxTOES1bFtbVqjTWwKDyP0CgCgYIKoZIzj0DAQehRANCAARoRlFHYxiOoYyy
NgCCTSrUclavb8tUUL774Lb07xPpjiVX0ce0PNwZ4XUd1q8YaJGzTDJzp6yKznuf
rvTCU3zw
-----END PRIVATE KEY-----